#!/usr/bin/env bash
#
# generate-catalog.sh — regenerate the skills cheat-sheet in README.md.
#
# Scans every SKILL.md, derives name + category (from folder path) + a one-line
# summary (first sentence of the description) + an invocation hint, and writes a
# Markdown table between the <!-- CATALOG:START --> / <!-- CATALOG:END --> markers
# in README.md. Idempotent — run it whenever skills are added/removed/moved.
#
# The meta-skills (god, concierge) do NOT depend on this file — they live-scan the
# repo. This catalog is a human convenience + fast index, kept regenerable so it
# never silently rots.
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
README="$REPO/README.md"
ROWS="$(mktemp)"; CAT="$(mktemp)"
trap 'rm -f "$ROWS" "$CAT"' EXIT

# Full description value from a SKILL.md frontmatter (handles inline + block scalar)
extract_desc() {
  awk '
    NR==1 && /^---/ {infm=1; next}
    infm && /^---/ {exit}
    infm && /^description:/ {
      line=$0; sub(/^description:[ \t]*/,"",line)
      if (line=="" || line ~ /^[>|][+-]?$/) { block=1; next }
      gsub(/^"/,"",line); gsub(/"$/,"",line); print line; done=1; exit
    }
    block {
      if ($0 ~ /^[^ \t]/) { exit }
      l=$0; sub(/^[ \t]+/,"",l)
      buf = (buf=="") ? l : buf" "l
    }
    END { if (block && !done) print buf }
  ' "$1"
}

# First sentence of a string (up to the first ". "); trims whitespace; strips pipes
first_sentence() {
  printf '%s' "$1" \
    | sed -E 's/([^.]*\.)[[:space:]].*/\1/' \
    | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//; s/\|/\//g'
}

# Collect one "category<TAB>name<TAB>summary<TAB>invoke" row per skill
while IFS= read -r smd; do
  dir="$(dirname "$smd")"
  rel="${dir#$REPO/}"
  name="$(basename "$rel")"
  category="$(dirname "$rel")"
  desc="$(extract_desc "$smd")"
  summary="$(first_sentence "$desc")"
  if grep -qE '^user-invokable:[[:space:]]*true' "$smd"; then invoke="\`/$name\`"; else invoke="auto"; fi
  printf '%s\t%s\t%s\t%s\n' "$category" "$name" "$summary" "$invoke" >> "$ROWS"
done < <(find "$REPO" -name SKILL.md -not -path '*/.git/*')

n="$(wc -l < "$ROWS" | tr -d ' ')"

# Build the catalog markdown (sorted by category, then name)
{
  echo "_Auto-generated by \`generate-catalog.sh\` — do not edit by hand. $n skills._"
  echo
  echo "| Skill | Category | What it does | Invoke |"
  echo "|---|---|---|---|"
  sort -t"$(printf '\t')" -k1,1 -k2,2 "$ROWS" | while IFS="$(printf '\t')" read -r category name summary invoke; do
    echo "| \`$name\` | \`$category\` | $summary | $invoke |"
  done
} > "$CAT"

# --print / --check: emit the catalog to stdout without touching README
# (used by the concierge audit to detect drift)
case "${1:-}" in
  --print|--check) cat "$CAT"; exit 0 ;;
esac

# Inject between the markers in README.md
if ! grep -q '<!-- CATALOG:START -->' "$README" || ! grep -q '<!-- CATALOG:END -->' "$README"; then
  echo "ERROR: README.md is missing the CATALOG markers." >&2
  exit 1
fi
awk -v catfile="$CAT" '
  /<!-- CATALOG:START -->/ { print; skip=1; while ((getline line < catfile) > 0) print line; close(catfile); next }
  skip && /<!-- CATALOG:END -->/ { skip=0 }
  !skip { print }
' "$README" > "$README.tmp" && mv "$README.tmp" "$README"

echo "Catalog regenerated: $n skills written to README.md"
